import {MODES,MODE_ORDER} from './modes.js';import {MODELS,newConversation,loadIndex,getIndex,getConversation,saveConversation,deleteConversation,setCloud,isCloud} from './store.js';import {renderMarkdown} from './markdown.js';import {extractArtifacts,htmlDocument} from './artifacts.js';
const $=s=>document.querySelector(s);let state={model:'x-ai/grok-4.6',mode:'balanced',streaming:true,busy:false,abort:false,conv:null,arts:[],art:null};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function toast(s){const x=$('#toast');x.textContent=s;x.hidden=false;setTimeout(()=>x.hidden=true,1800)}
function modelName(id){return MODELS.find(x=>x.id===id)?.name||id}
function renderModes(){$('#modeRow').innerHTML=MODE_ORDER.map(k=>'<button class="mode '+(state.mode===k?'active':'')+'" data-mode="'+k+'">'+MODES[k].label+'</button>').join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderModes()})}
function renderModels(){$('#modelSelect').innerHTML=MODELS.map(m=>'<option value="'+m.id+'">'+m.name+'</option>').join('');$('#modelSelect').value=state.model}
function renderList(){const q=$('#searchInput').value.toLowerCase();$('#convList').innerHTML=getIndex().filter(x=>(x.title||'').toLowerCase().includes(q)).map(x=>'<button class="conv '+(state.conv?.id===x.id?'active':'')+'" data-id="'+x.id+'">'+esc(x.title||'ไม่มีชื่อ')+'<small>'+x.count+' ข้อความ</small></button>').join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const c=await getConversation(b.dataset.id);if(c){state.conv=c;state.model=c.model;state.mode=c.mode||'balanced';renderModels();renderModes();renderMessages();renderList()}})}
function renderMessages(){const box=$('#messages');if(!state.conv?.messages.length){box.innerHTML='<div class="message"><div class="bubble md"><h2>Grok Chat</h2><p>พร้อมใช้งานด้วย Puter.js — เลือกโหมดแล้วส่งข้อความได้เลย</p></div></div>';return}box.innerHTML=state.conv.messages.map(m=>'<div class="message '+(m.role==='user'?'user':'')+'"><div class="bubble md">'+renderMarkdown(m.content)+'</div></div>').join('');box.scrollTop=box.scrollHeight}
function syncView(){state.arts=extractArtifacts(state.conv?.messages||[]);$('#viewBadge').textContent=state.arts.length;$('#artifactSelect').innerHTML=state.arts.map(a=>'<option value="'+a.id+'">'+esc(a.name)+'</option>').join('');if(state.arts.length&&!state.art)state.art=state.arts[0].id;renderView()}
function currentArt(){return state.arts.find(a=>a.id===state.art)||state.arts[0]}
function renderView(){const a=currentArt(),body=$('#viewBody');if(!a){body.innerHTML='<div class="artifact-code">ยังไม่มีผลลัพธ์</div>';return}$('#artifactSelect').value=a.id;if(a.renderable&&a.kind!=='markdown'){const blob=new Blob([htmlDocument(a)],{type:'text/html'});body.innerHTML='<iframe class="artifact-frame" sandbox="allow-scripts" src="'+URL.createObjectURL(blob)+'"></iframe>'}else body.innerHTML='<pre class="artifact-code">'+esc(a.code)+'</pre>'}
function setTab(t){$('#messages').hidden=t!=='chat';$('#viewPane').hidden=t!=='view';$('#tabChat').classList.toggle('active',t==='chat');$('#tabView').classList.toggle('active',t==='view');if(t==='view')renderView()}
function textOf(r){if(typeof r==='string')return r;if(r?.message?.content)return Array.isArray(r.message.content)?r.message.content.map(x=>x.text||'').join(''):r.message.content;if(r?.text)return r.text;return ''}
async function send(){const input=$('#input'),q=input.value.trim();if(!q||state.busy)return;input.value='';state.busy=true;state.abort=false;if(!state.conv)state.conv=newConversation(state.model);state.conv.model=state.model;state.conv.mode=state.mode;if(!state.conv.title)state.conv.title=q.slice(0,55);state.conv.messages.push({role:'user',content:q,ts:Date.now()});renderMessages();const pending={role:'assistant',content:'',ts:Date.now()};state.conv.messages.push(pending);renderMessages();try{const mode=MODES[state.mode];if(mode.agents){let drafts=[];for(const a of mode.agents){if(state.abort)break;try{const r=await puter.ai.chat([{role:'system',content:a.system},{role:'user',content:q}],{model:a.model});drafts.push(a.role+': '+textOf(r))}catch(e){}}const r=await puter.ai.chat([{role:'system',content:mode.synth},{role:'user',content:q+'\\n\\n'+drafts.join('\\n\\n')}],{model:mode.model,stream:state.streaming});if(state.streaming){for await(const p of r){if(state.abort)break;pending.content+=textOf(p);renderMessages()}}else pending.content=textOf(r)}else{const msgs=[{role:'system',content:mode.system},...state.conv.messages.filter(x=>x!==pending)];const r=await puter.ai.chat(msgs,{model:state.model,stream:state.streaming});if(state.streaming){for await(const p of r){if(state.abort)break;pending.content+=textOf(p);renderMessages()}}else pending.content=textOf(r)}}catch(e){pending.content='เกิดข้อผิดพลาด: '+(e?.message||'ไม่สามารถเรียกโมเดลได้')}state.busy=false;if(isCloud())await saveConversation(state.conv);syncView();renderList();renderMessages()}
$('#sendBtn').onclick=send;$('#stopBtn').onclick=()=>state.abort=true;$('#input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#newChatBtn').onclick=()=>{state.conv=newConversation(state.model);state.conv.mode=state.mode;renderMessages();renderList();setTab('chat')};$('#clearBtn').onclick=async()=>{if(state.conv){await deleteConversation(state.conv.id);state.conv=newConversation(state.model);renderMessages();renderList();syncView()}};$('#searchInput').oninput=renderList;$('#modelSelect').onchange=e=>{state.model=e.target.value;if(state.conv)state.conv.model=state.model};$('#tabChat').onclick=()=>setTab('chat');$('#tabView').onclick=()=>setTab('view');$('#artifactSelect').onchange=e=>{state.art=e.target.value;renderView()};$('#streamToggle').onclick=()=>{state.streaming=!state.streaming;toast(state.streaming?'เปิดสตรีมมิ่ง':'ปิดสตรีมมิ่ง')};$('#artCopy').onclick=()=>{const a=currentArt();if(a)navigator.clipboard.writeText(a.code).then(()=>toast('คัดลอกแล้ว'))};$('#artDownload').onclick=()=>{const a=currentArt();if(!a)return;const u=URL.createObjectURL(new Blob([a.code],{type:'text/plain'})),x=document.createElement('a');x.href=u;x.download=a.name;x.click();URL.revokeObjectURL(u)};$('#artNewTab').onclick=()=>{const a=currentArt();if(a)window.open(URL.createObjectURL(new Blob([htmlDocument(a)],{type:'text/html'})),'_blank')};$('#openSidebar').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');
(async()=>{state.conv=newConversation(state.model);renderModels();renderModes();renderMessages();renderList();syncView();try{const signed=puter.auth.isSignedIn();setCloud(signed);if(signed){await loadIndex();renderList();$('#authBox').innerHTML='<button class="auth" id="signout">ออกจากระบบ · '+esc((await puter.auth.getUser())?.username||'ผู้ใช้')+'</button>';$('#signout').onclick=()=>puter.auth.signOut().then(()=>location.reload())}else $('#authBox').innerHTML='<button class="auth" id="signin">ลงชื่อเข้าใช้ Puter เพื่อบันทึกแชท</button>';}catch(e){}$('#signin')?.addEventListener('click',()=>puter.auth.signIn().then(()=>location.reload()))})();